-- ============================================================================
-- V1__init_schema.sql
-- Sistema Corporativo de Gestão de Condomínios e Contratos (Construção Civil)
-- NENHUM dado fictício ou sementes pré-cadastradas: Apenas estrutura DDL.
-- ============================================================================

-- 1. Empresas (Construtoras / Incorporadoras)
CREATE TABLE companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cnpj VARCHAR(18) NOT NULL UNIQUE,
    corporate_name VARCHAR(150) NOT NULL,
    trade_name VARCHAR(150) NOT NULL,
    state_registration VARCHAR(30),
    email VARCHAR(100),
    phone VARCHAR(20),
    zip_code VARCHAR(10),
    street VARCHAR(150),
    number VARCHAR(20),
    complement VARCHAR(100),
    neighborhood VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(2),
    default_penalty_percent NUMERIC(5, 2) NOT NULL DEFAULT 2.00,
    default_interest_percent_monthly NUMERIC(5, 2) NOT NULL DEFAULT 1.00,
    default_grace_days INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

-- 2. Usuários do Sistema
CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(30) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    company_id BIGINT REFERENCES companies(id),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
CREATE INDEX idx_users_email ON users(email);

-- 3. Condomínios e Empreendimentos
CREATE TABLE condominiums (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    name VARCHAR(150) NOT NULL,
    cnpj VARCHAR(18),
    type VARCHAR(30) NOT NULL,
    construction_status VARCHAR(30) NOT NULL,
    registration_number VARCHAR(50),
    permit_number VARCHAR(50),
    zip_code VARCHAR(10),
    street VARCHAR(150),
    number VARCHAR(20),
    complement VARCHAR(100),
    neighborhood VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(2),
    notes TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE INDEX idx_condominiums_company ON condominiums(company_id);

-- 4. Blocos / Torres / Quadras
CREATE TABLE building_blocks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    condominium_id BIGINT NOT NULL REFERENCES condominiums(id),
    name VARCHAR(100) NOT NULL,
    total_floors INT,
    notes TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
CREATE INDEX idx_building_blocks_condo ON building_blocks(condominium_id);

-- 5. Unidades / Apartamentos / Lotes
CREATE TABLE units (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    building_block_id BIGINT NOT NULL REFERENCES building_blocks(id),
    unit_number VARCHAR(30) NOT NULL,
    floor_number INT,
    typology VARCHAR(50),
    private_area NUMERIC(10, 2),
    total_area NUMERIC(10, 2),
    parking_spaces INT DEFAULT 0,
    ideal_fraction NUMERIC(8, 6),
    base_price NUMERIC(15, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    notes TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT uk_block_unit UNIQUE (building_block_id, unit_number)
);
CREATE INDEX idx_units_block ON units(building_block_id);
CREATE INDEX idx_units_status ON units(status);

-- 6. Clientes e Responsáveis Financeiros
CREATE TABLE customers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    customer_type VARCHAR(20) NOT NULL,
    name VARCHAR(150) NOT NULL,
    document VARCHAR(20) NOT NULL,
    state_or_id_document VARCHAR(30),
    marital_status VARCHAR(30),
    profession VARCHAR(100),
    spouse_name VARCHAR(150),
    spouse_document VARCHAR(20),
    email VARCHAR(120) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    secondary_phone VARCHAR(20),
    zip_code VARCHAR(10),
    street VARCHAR(150),
    number VARCHAR(20),
    complement VARCHAR(100),
    neighborhood VARCHAR(100),
    city VARCHAR(100),
    state VARCHAR(2),
    lgpd_consent BOOLEAN NOT NULL DEFAULT FALSE,
    lgpd_consent_date TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT uk_company_customer_doc UNIQUE (company_id, document)
);
CREATE INDEX idx_customers_document ON customers(document);

-- 7. Contratos de Compra e Venda
CREATE TABLE contracts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES companies(id),
    customer_id BIGINT NOT NULL REFERENCES customers(id),
    unit_id BIGINT NOT NULL REFERENCES units(id),
    contract_number VARCHAR(50) NOT NULL UNIQUE,
    contract_date DATE NOT NULL,
    total_amount NUMERIC(15, 2) NOT NULL,
    down_payment NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    balance_amount NUMERIC(15, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    adjustment_index VARCHAR(30),
    penalty_percent NUMERIC(5, 2) NOT NULL DEFAULT 2.00,
    interest_percent_monthly NUMERIC(5, 2) NOT NULL DEFAULT 1.00,
    grace_days INT NOT NULL DEFAULT 0,
    notes TEXT,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
CREATE INDEX idx_contracts_customer ON contracts(customer_id);
CREATE INDEX idx_contracts_unit ON contracts(unit_id);
CREATE INDEX idx_contracts_number ON contracts(contract_number);

-- 8. Plano Financeiro do Contrato
CREATE TABLE financial_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL UNIQUE REFERENCES contracts(id),
    down_payment_installments_count INT NOT NULL DEFAULT 1,
    monthly_installments_count INT NOT NULL DEFAULT 1,
    first_due_date DATE NOT NULL,
    due_day_of_month INT NOT NULL,
    has_intermediate_installments BOOLEAN NOT NULL DEFAULT FALSE,
    intermediate_installments_count INT DEFAULT 0,
    intermediate_frequency_months INT DEFAULT 6,
    intermediate_amount_per_installment NUMERIC(15, 2) DEFAULT 0.00,
    keys_installment_amount NUMERIC(15, 2) DEFAULT 0.00,
    keys_due_date DATE,
    created_at TIMESTAMP NOT NULL
);

-- 9. Parcelas do Contrato
CREATE TABLE installments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contracts(id),
    installment_number INT NOT NULL,
    total_installments INT NOT NULL,
    installment_type VARCHAR(30) NOT NULL,
    due_date DATE NOT NULL,
    business_due_date DATE NOT NULL,
    base_amount NUMERIC(15, 2) NOT NULL,
    penalty_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    interest_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    discount_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    paid_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    balance_amount NUMERIC(15, 2) NOT NULL,
    status VARCHAR(30) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    notes VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);
CREATE INDEX idx_installments_contract ON installments(contract_id);
CREATE INDEX idx_installments_due_date ON installments(due_date);
CREATE INDEX idx_installments_business_due ON installments(business_due_date);
CREATE INDEX idx_installments_status ON installments(status);

-- 10. Pagamentos e Baixas
CREATE TABLE payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    installment_id BIGINT NOT NULL REFERENCES installments(id),
    payment_date DATE NOT NULL,
    amount_received NUMERIC(15, 2) NOT NULL,
    penalty_applied NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    interest_applied NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    discount_applied NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    payment_method VARCHAR(30) NOT NULL,
    transaction_reference VARCHAR(100),
    registered_by_user_id BIGINT REFERENCES users(id),
    notes TEXT,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_payments_installment ON payments(installment_id);

-- 11. Renegociações de Débito
CREATE TABLE renegotiations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    contract_id BIGINT NOT NULL REFERENCES contracts(id),
    renegotiation_date DATE NOT NULL,
    previous_outstanding_balance NUMERIC(15, 2) NOT NULL,
    agreed_interest_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    agreed_discount_amount NUMERIC(15, 2) NOT NULL DEFAULT 0.00,
    new_total_amount NUMERIC(15, 2) NOT NULL,
    new_installments_count INT NOT NULL,
    status VARCHAR(30) NOT NULL,
    reason TEXT NOT NULL,
    performed_by_user_id BIGINT REFERENCES users(id),
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_renegotiations_contract ON renegotiations(contract_id);

-- Tabela associativa entre renegociação e parcelas substituídas
CREATE TABLE renegotiation_installments (
    renegotiation_id BIGINT NOT NULL REFERENCES renegotiations(id),
    installment_id BIGINT NOT NULL REFERENCES installments(id),
    PRIMARY KEY (renegotiation_id, installment_id)
);

-- 12. Trilha de Auditoria
CREATE TABLE audit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(50) NOT NULL,
    entity_name VARCHAR(50) NOT NULL,
    entity_id VARCHAR(50),
    performed_by_email VARCHAR(120),
    ip_address VARCHAR(50),
    details TEXT,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_audit_logs_entity ON audit_logs(entity_name, entity_id);
CREATE INDEX idx_audit_logs_created ON audit_logs(created_at);
